services:
  app:
    build:
      context: .
      dockerfile_inline: |
        FROM ruby:3.2.2-slim-bullseye
        WORKDIR /app
        RUN apt-get update && apt-get install -y \
                sshpass \
            && \
            gem install rubocop --no-document && \
            apt-get clean && \
            rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
        CMD []
    depends_on:
      - googlecloud
    environment:
      TASK_GOOGLECLOUD_IN_CONTAINER: "1"
    volumes:
      - .:/app
  googlecloud:
    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/x86_64 gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
        WORKDIR /uploads
        RUN apt-get update && apt-get install -y \
                openssh-server \
            && \
            mkdir /var/run/sshd && \
            echo "root:secret" | chpasswd && \
            sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/" /etc/ssh/sshd_config
        EXPOSE 22
        CMD ["/usr/sbin/sshd", "-D"]
    volumes:
      - .:/app
